name: CI

on: [push, pull_request]

jobs:

  tests:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        otp: ['19.3', '21.3', 24]
    runs-on: ubuntu-20.04
    container:
      image: erlang:${{ matrix.otp }}
    steps:
    - uses: actions/checkout@v2
    - run: make
    - run: REBAR=rebar3 ERLTIDY=true make
    - run: REBAR=rebar3 make spec
    - run: REBAR=rebar3 make xdata
    - run: REBAR=rebar3 make
    - run: REBAR=rebar3 make xref
    - run: REBAR=rebar3 make dialyzer
    - run: rebar3 eunit -v
    - uses: stefanzweifel/git-auto-commit-action@v4
      if: matrix.otp == 24 && github.event_name == 'push'
      with:
        commit_message: Automatic changes "make spec xdata"

  cover:
    name: Cover
    needs: [tests]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: ./configure --enable-gcov
    - run: REBAR=rebar3 make
    - run: REBAR=rebar3 make spec
    - run: REBAR=rebar3 make xdata
    - run: REBAR=rebar3 make
    - run: rebar3 eunit -v
    - run: pip install --user cpp-coveralls
    #- run: cpp-coveralls -b `pwd` --verbose --gcov-options '\-lp' --dump c.json
    - name: Send to Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        #ADDJSONFILE=c.json COVERALLS=true rebar3 as test coveralls send
        COVERALLS=true rebar3 as test coveralls send
        curl -v -k https://coveralls.io/webhook \
             --header "Content-Type: application/json" \
             --data '{"repo_name":"$GITHUB_REPOSITORY",
                      "repo_token":"$GITHUB_TOKEN",
                      "payload":{"build_num":$GITHUB_RUN_ID,
                                 "status":"done"}}'
